gestionStage/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # racine et page par defaut, pages classiques
    url(r'^/?$',"gestionStage.views.show_main", name="accueil"),
    url(r'^login/$', "gestionStage.forms.login_page", name="login"),
    url(r'^logout/$', "gestionStage.forms.logout_action", name="logout"),
    url(r'^oups/$',"gestionStage.views.oups",name="oups"),
    url(r'^recherche/$',"gestionStage.views.search",name="search"),

    # app entreprise
    url(r'^entreprise/', include('entreprise.urls')),
    url(r'^visiter/$', "entreprise.views.show_visiter", name="visiter"),

    # app stage
    url(r'^stage/', include('stage.urls')),

    # app planning
    url(r'^planning/', include('planning.urls')),


    url(r'^monProfilEtudiant/?$',"stage.views.monProfilEtu", name="monProfil"),
    url(r'^etudiant/(?P<pk>\d+)$',"stage.views.detailsEtudiant", name="detailsEtudiant"),
    url(r'^etudiant/modifier/(?P<pk>\d+)$',"stage.views.modifEtudiant", name="modifEtudiant"),

    url(r'^monProfilEnseignant/?$',"stage.views.monProfilEns", name="monProfil"),
    url(r'^enseignant/(?P<pk>\d+)$',"stage.views.detailsEnseignant", name="detailsEnseignant"),
    url(r'^enseignant/modifier/(?P<pk>\d+)$',"stage.views.modifEnseignant", name="modifEnseignant"),

    url(r'^findData/?$', "gestionStage.views.find_data", name="find_data")


)

planning/urls.py
from django.conf.urls import patterns, include, url


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
   
	# Planning
    url(r'^$', "planning.views.show_planning", name="show_planning"),
    url(r'^(?P<pk>\d+)$', "planning.views.show_soutenance", name="show_soutenance"),
    url(r'^find/?$', "planning.views.find_planning", name="find_planning"),

    url(r'^ajout/?$', "planning.views.addSoutenance", name="addSoutenance"),
    url(r'^ajouterSalle/?$', "planning.views.addSalle", name="addSalle"),

    url(r'^modifier/(?P<pk>\d+)$', "planning.views.editSoutenance", name="editSoutenance"),
    url(r'^supprimer/?$',"planning.views.delSoutenance", name="delSoutenance"),
)

stage/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'gestionStage.views.home', name='home'),
    # url(r'^gestionStage/', include('gestionStage.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
   
    url(r'^/?$',"stage.views.show_stages"),
    url(r'^(?P<pk>\d+)$',"stage.views.show_detail_stage", name="stage"),
    url(r'^modifier/(?P<pk>\d+)$',"stage.views.modifStage", name="modifStage"),
    url(r'^monStage/?$',"stage.views.monStage", name="theStage"),
    url(r'^ajouter/?$',"stage.views.addStage", name="addStage"),
    url(r'^supprimer/?$',"stage.views.delStage", name="delStage"),
    url(r'^logiciel/$',"stage.views.addLogiciel",name="addLogiciel"),
    url(r'^personne-ext/$',"stage.views.addPersonneExt",name="addPersonneExt"),
    url(r'^ok/?$',"stage.views.stage_operationEffectuee", name="stageOperationEffectuee"),
    url(r'^valider/?$',"stage.views.validerStage", name="validerStage"),
    url(r'^detailsvalider/(?P<pk>\d+)$',"stage.views.detailsValiderStage", name="detailsValiderStage"),
    url(r'^validerenbase/(?P<pk>\d+)$',"stage.views.validerStageEnBase", name="validerStageEnBase"),

    url(r'^offrestage/?$',"stage.views.showOffres", name="showOffres"),
    url(r'^offrestage/(?P<pk>\d+)$',"stage.views.detailsOffreStage", name="detailsOffreStage"),
    url(r'^offrestage/modifier/(?P<pk>\d+)$',"stage.views.modifOffreStage", name="modifOffreStage"),
    url(r'^offrestage/ajouter/?$',"stage.views.addOffreStage", name="addOffreStage"),
    url(r'^offrestage/supprimer/?$',"stage.views.delOffreStage", name="delOffreStage"),
    url(r'^offrestage/ok/?$',"stage.views.offreStage_operationEffectuee", name="offreStageOperationEffectuee"),
    url(r'^offrestage/valider/?$',"stage.views.validerOffreStage", name="validerOffreStage"),
    url(r'^offrestage/detailsvalider/(?P<pk>\d+)$',"stage.views.detailsValiderOffreStage", name="detailsValiderOffreStage"),
    url(r'^offrestage/validerenbase/(?P<pk>\d+)$',"stage.views.validerOffreStageEnBase", name="validerOffreStageEnBase"),
    #url(r'^offrestage/postuler/(?P<pk>\d+)$',"stage.views.postuler", name="postuler"),
    url(r'^offrestage/prendreOffre/(?P<pk>\d+)$',"stage.views.prendreOffre", name="prendreOffre"),
)

planning/models.py
from django.db import models

from stage.models import Stage

class Salle(models.Model):
	num = models.CharField(max_length=5, primary_key=True)

	def __str__(self):
		return "%s" % (self.num)

class Soutenance(models.Model):
	idSoutenance = models.AutoField(primary_key=True)
	stage = models.ForeignKey(Stage, unique=True)
	datePassage = models.DateTimeField(verbose_name="Date de passage")
	dateFinPrevu = models.DateTimeField(verbose_name="Fin prévu")
	salle = models.ForeignKey(Salle, unique_for_date="datePassage")

	def __str__(self):
		return "%s" % (self.stage.intitule)

	def natural_key(self):
		return (self.idSoutenance, datePassage) + (self.stage.natural_key(),)

planning/forms.py
from django import forms
from django.forms import ModelForm

from planning.models import Soutenance, Salle
from stage.models import Stage

class SoutenanceSelection(ModelForm):
    class Meta:
        model = Soutenance
        exclude = ['idSoutenance', 'stage', 'salle']

class SoutenanceForm(ModelForm):
    stage = forms.ModelChoiceField(queryset=Stage.objects.filter(valideStage=True))

    class Meta:
        model = Soutenance

class SalleForm(ModelForm):
	class Meta:
		model = Salle

class supprimerSoutenanceForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(supprimerSoutenanceForm, self).__init__(*args, **kwargs)
        self.fields['soutenanceslots'].label = "Selectionnez les soutenances à supprimer"
    # You can change the queryset in the __init__ method, but this should be a nice basis
        
    soutenanceslots = forms.ModelMultipleChoiceField(
        queryset=Soutenance.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
        required=False)

    def save(self):
        # make sure you do a form.is_valid() before trying to save()
        for soutenance in self.cleaned_data['soutenanceslots']:
            soutenance.delete()
    def list(self):
        # make sure you do a form.is_valid() before trying to save()
        for soutenance in self.cleaned_data['soutenanceslots']:
            print(soutenance)

    class Meta:
        model = Soutenance
        fields ='soutenanceslots'

stage/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from django import forms
from django.forms.extras.widgets import SelectDateWidget
from stage.models import *
from django.shortcuts import render
from django.contrib.auth.models import User


class StageFormEtu(ModelForm):
    etudiant = forms.ModelChoiceField(queryset=Etudiant.objects.all(),
            widget=forms.HiddenInput())
    dateDebut = forms.DateField(widget=SelectDateWidget())
    dateFin = forms.DateField(widget=SelectDateWidget())

    class Meta:
        model = Stage
        exclude = ['valideOffreStage', 'valideStage']


class StageForm(ModelForm):
    dateDebut = forms.DateField(widget=SelectDateWidget())
    dateFin = forms.DateField(widget=SelectDateWidget())

    class Meta:
        model = Stage
        exclude = ['valideOffreStage', 'valideStage']


class supprimeStageForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(supprimeStageForm, self).__init__(*args, **kwargs)
        self.fields['stageslots'].label = "Selectionnez les stages à supprimer"
    # You can change the queryset in the __init__ method, but this should be a nice basis
        
    stageslots = forms.ModelMultipleChoiceField(queryset=Stage.objects.all(), widget=forms.CheckboxSelectMultiple(),required=False)

    def save(self):
        # make sure you do a form.is_valid() before trying to save()
        for stageslot in self.cleaned_data['stageslots']:
            stageslot.delete()
    def list(self):
        # make sure you do a form.is_valid() before trying to save()
        for stageslot in self.cleaned_data['stageslots']:
            print(stageslot)
    class Meta:
        model = Stage
        fields ='stageslots'


class PersonneExtForm(ModelForm):
    class Meta:
        model = PersonneExterieure

class LogicielForm(ModelForm):
    class Meta:
        model = Logiciel   
        

class OffreStageForm(ModelForm):
    class Meta:
        model = OffreStage
        exclude = ['valideOffreStage']

class supprimeOffreStageForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(supprimeOffreStageForm, self).__init__(*args, **kwargs)
        self.fields['offrestagelots'].label = "Selectionnez les offres de stage à supprimer"
    # You can change the queryset in the __init__ method, but this should be a nice basis
        
    offrestagelots = forms.ModelMultipleChoiceField(queryset=OffreStage.objects.filter(valideOffreStage=True) | OffreStage.objects.filter(valideOffreStage=False), widget=forms.CheckboxSelectMultiple(),required=False)

    def save(self):
        # make sure you do a form.is_valid() before trying to save()
        for offrestagelots in self.cleaned_data['offrestagelots']:
            offrestagelots.delete()
    def list(self):
        # make sure you do a form.is_valid() before trying to save()
        for offrestagelots in self.cleaned_data['offrestagelots']:
            print(offrestagelots)
    class Meta:
        model = Stage
        fields ='offrestagelots'



class EtudiantForm(ModelForm):
    class Meta:
        model = Etudiant
        exclude = ['postulant']


class EnseignantForm(ModelForm):
    class Meta:
        model = Enseignant

planning/views.py
from django.shortcuts import HttpResponseRedirect, HttpResponse
from django.forms import ModelForm
from django.template import RequestContext
from django.core import serializers
from django.core.context_processors import csrf

from datetime import datetime

from gestionStage.shortcuts import render
from stage.models import Stage, Etudiant, Enseignant, PersonneExterieure
from planning.models import Soutenance, Salle
from planning.forms import SoutenanceSelection, SoutenanceForm, SalleForm, supprimerSoutenanceForm

from django.contrib.auth.models import User

import json

def show_planning(request):
	return render(request,
		"planning/planning.html", {
			'form' : SoutenanceForm(),
			'salleForm' : SalleForm()})

def show_soutenance(request, pk):
	return render(
		request,
		"planning/soutenance.html",
		{'soutenance' : Soutenance.objects.get(idSoutenance=pk)})

def addSoutenance(request):
	try:
		# Vérification des permissions de l'utilisateur
		user = User.objects.get(username=request.user.username)
	except:
		return HttpResponseRedirect('/oups/')
	permissions = user.get_all_permissions()
	
	if ("planning.add_soutenance" in permissions):

		if request.method == 'POST':  				# Si une requête POST a été passée
			form = SoutenanceForm(request.POST)  	# On récupère les données
			
			if form.is_valid(): 					# Si les données reçues sont valides
				form.save()
				try:
					request.POST['ajax']
					return HttpResponse(
						serializers.serialize(
							"json",
							Soutenance.objects.filter(stage=
								Stage.objects.get(pk=request.POST['stage'])),
							indent = 2, 
							use_natural_keys=True
						),
						mimetype="application/json")
				except:
					return HttpResponseRedirect('/planning/')
			else:									# Si les données reçues sont invalides
				con = { 'actionAFaire' : 'Ajouter', 'form' : form}
				return render(request,'planning/forms.html', con)

		else: 										# Pas de requête POST
			form = SoutenanceForm()  				# On crée un formulaire vide
			con = { 'actionAFaire' : 'Ajouter', 'form' : form}
			return render(request,'planning/forms.html', con)
	
	else:
		return HttpResponseRedirect('/oups/')


def addSalle(request):
	try:
		# Vérification des permissions de l'utilisateur
		user = User.objects.get(username=request.user.username)
	except:
		return HttpResponseRedirect('/oups/')
	permissions = user.get_all_permissions()
	
	if ("planning.add_salle" in permissions):

		if request.method == 'POST':  				# S'il s'agit d'une requête POST
			form = SalleForm(request.POST)  	# Nous reprenons les données

			if form.is_valid(): 					# Nous vérifions que les données envoyées sont valides
				form.save()
				try:
					request.POST['ajax']
					return HttpResponse(
						serializers.serialize(
							"json",
							Salle.objects.filter(num=request.POST['num'])
						),
						mimetype="application/json")
				except:
					return HttpResponseRedirect('/planning/')
		else:
			form = SalleForm()

		con = { 'actionAFaire' : 'Ajouter', 'form' : form}
		return render(request,'planning/forms.html', con)

	else:
		return HttpResponseRedirect('/oups/')

def editSoutenance(request, pk):
	try:
		# Vérification des permissions de l'utilisateur
		user = User.objects.get(username=request.user.username)
	except:
		return HttpResponseRedirect('/oups/')
	permissions = user.get_all_permissions()
	
	if ("planning.change_soutenance" in permissions):
		if request.method == 'POST':  # S'il s'agit d'une requête POST
			form = SoutenanceForm(request.POST, instance=Soutenance.objects.get(pk=pk))
			if form.is_valid(): # Nous vérifions que les données envoyées sont valides
				form.save()
				return HttpResponseRedirect('/planning/' + pk)
			else: # Si ce n'est pas du POST, c'est probablement une requête GET
				print("Error")

		return render(request,
			'planning/forms.html',
			{ 'actionAFaire' : 'Modifier',
				'form' : SoutenanceForm(instance=Soutenance.objects.get(pk=pk))})

	else:
		return HttpResponseRedirect('/oups/')

def delSoutenance(request):
	try:
		# Vérification des permissions de l'utilisateur
		user = User.objects.get(username=request.user.username)
	except:
		return HttpResponseRedirect('/oups/')
	permissions = user.get_all_permissions()

	if ("planning.delete_soutenance" in permissions):
		suppForm = supprimerSoutenanceForm()
		con ={'form': suppForm, 'actionAFaire' : 'Supprimer'}
		con.update(csrf(request))

		if len(request.POST) > 0:
			suppForm = supprimerSoutenanceForm(request.POST)
			con = {'form': suppForm}
			if suppForm.is_valid():   
				suppForm.save()
				return HttpResponseRedirect("/planning/")
		else:
			return render(request,'planning/forms.html', con)

	else:
		return HttpResponseRedirect('/oups')

# méthode pour AJAX ! ! !
def find_planning(request):
	debutDeJournee = datetime.strptime(request.GET['dateD'], "%Y-%m-%d");
	finDeJournee = datetime.strptime(request.GET['dateF'], "%Y-%m-%d");

	res = serializers.serialize(
		"json",
		Soutenance.objects.filter(
			datePassage__lt=finDeJournee,
			datePassage__gt=debutDeJournee
		).order_by('datePassage', 'salle'),
		indent = 2, 
		use_natural_keys=True
	)

	return HttpResponse(res, mimetype="application/json")

planning/templates/planning/forms.html
{% extends "base.html" %}
{% block title %}{{ block.super }} | {{ actionAFaire }} {% endblock %}
{% block main %}
	<form action="" method="post">{% csrf_token %}
	<table>
		{{ form.as_table }}
		</table>
		<input class="btn btn-success" type="submit" value="{{ actionAFaire }}" />
	</form>
{% endblock %}
{% block libraries %}{{ block.super }}
	<link rel="stylesheet" type="text/css" href="/static/css/jquery.datetimepicker.css" media="screen">
	<script type="text/javascript" src="/static/js/jquery-ui-1.10.4.custom.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery.datetimepicker.js"></script>
	<script type="text/javascript" src="/static/js/utils.js"></script>
{% endblock %}
{% block js %}
	becomeDateTimePicker("#id_datePassage");
	becomeDateTimePicker('#id_dateFinPrevu');
	{% if "planning.add_salle" in user.get_all_permissions %}
		publierBoutonAjouter('#id_salle', '/planning/ajouterSalle');
	{% endif %}
	active_tab="#tab-planning"
{% endblock %}

planning/templates/planning/planning.html
{% extends "base.html" %}
{% block title %}{{ block.super }} | Planning {% endblock %}
{% block main %}
	<h1>Planning</h1>
	<br/>

	{% if "planning.add_soutenance" in user.get_all_permissions %}
	<button id="createSoutenance">Create new user</button>
	<div id="soutenanceForm">
		<form action="" id="soutenance_form" method="post">{% csrf_token %}
			<table>
				{{ form.as_table }}
				<input type="hidden" value="true" name="ajax" />
			</table>
		</form>
	</div>
	<div id="salleForm">
		<form action="" id="salle_form" method="post">{% csrf_token %}
			<table>
				{{ salleForm.as_table }}
			</table>
			<input type="hidden" value="true" name="ajax" />
		</form>
	</div>
	{% endif %}

	<div>
		<label for="id_dateDebut">Soutenance du</label>
		<input id="id_dateDebut" />
		<label for="id_dateFin"> au </label>
		<input id="id_dateFin" />
	</div>
<div id="planning"></div>
{% endblock %}
{% block libraries %}{{ block.super }}
	<link href='/static/css/fullcalendar.css' rel='stylesheet' />
	<link href='/static/css/fullcalendar.print.css' rel='stylesheet' media='print' />
	<link rel="stylesheet" type="text/css" href="/static/css/smoothness/jquery-ui-1.10.4.custom.min.css" media="screen">
	<link rel="stylesheet" type="text/css" href="/static/css/jquery.datetimepicker.css" media="screen">

	<script type="text/javascript" src="/static/js/jquery-ui-1.10.4.custom.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery.datetimepicker.js"></script>
	<script type="text/javascript" src='/static/js/fullcalendar.min.js'></script>
	<script type="text/javascript" src="/static/js/utils.js"></script>
	<script type="text/javascript" src="/static/js/planning.js"></script>
{% endblock %}
{% block js %}

	$( document ).ready( function() {

		{% if "planning.add_soutenance" in user.get_all_permissions %}

		$('#createSoutenance').css('visibility', 'hidden');

		becomeDateTimePicker('#id_datePassage');
		becomeDateTimePicker('#id_dateFinPrevu');

		submitAjax("#soutenance_form", '{% url 'addSoutenance' %}',
			function(data){
				try{ 
					var nouvelObjet = extractSoutenanceCalendarData(data)[0];
					$('#planning').fullCalendar(
						'renderEvent',
						nouvelObjet,
						true // make the event "stick"
					);
				} catch(err) {
					$('#soutenance_form').html(data
						.split('<form action="" method="post">')[1]
						.split('</form>')[0]);
					$('input[type=submit]').remove();
					$('#soutenance_form').append('<input type="hidden" value="true" name="ajax" />');
					publierBoutonAjouterDialog('#id_salle',
						'#id_addSalle',
						'#salle_form',
						850, 400,
						function(){
							$('#salle_form').submit();
						});
					$("#createSoutenance").click();
				}
			});

		submitAjax("#salle_form", '{% url 'addSalle' %}',
			function(data){
				if(typeof data != "string"){
					$('#id_salle').append('<option value="' +
						data[0]['pk'] + '">' + 
						data[0]['pk'] + '</option>');
				} else {
					$('#salle_form').html(data.split('<form action="" method="post">')[1].split('</form>')[0]);
					$('input[type=submit]').remove();
					$('#salle_form').append('<input type="hidden" value="true" name="ajax" />');
					$("#id_addSalle").click();
				}
			});

		genDialogForm("#soutenance_form", "#createSoutenance", 850, 400, function(){
			$('#soutenance_form').submit();
		});
		publierBoutonAjouterDialog('#id_salle', '#id_addSalle', "#salle_form", 850, 400, function(){
			$('#salle_form').submit();
		});

		{% endif %}

		becomeDatePicker('#id_dateDebut');
		becomeDatePicker('#id_dateFin');

		$('#id_dateDebut').change(function(){
			if($('#id_dateFin').val() && testArgs()){
				{% if "planning.add_soutenance" in user.get_all_permissions %}
				updatePlanning(true);
				{% else %}
				updatePlanning(false);
				{% endif %}
			}
		});
		$('#id_dateFin').change(function(){
			if($('#id_dateDebut').val() && testArgs()){
				{% if "planning.add_soutenance" in user.get_all_permissions %}
				updatePlanning(true);
				{% else %}
				updatePlanning(false);
				{% endif %}
			}
		});
	});

	active_tab="#tab-planning"
{% endblock %}

planning/templates/planning/soutenance.html
{% extends "base.html" %}
{% block title %}{{ block.super }} | Soutenance {% endblock %}
{% block main %}
<div class="menu col-xs-12 col-sm-2 col-lg-2 pull-right">
	{% if "planning.change_soutenance" in user.get_all_permissions %}
	<a href="{% url 'editSoutenance' pk=soutenance.idSoutenance %}" class="btn btn-primary">Modifier</a><br />
	{% endif %}
	{% if "planning.delete_soutenance" in user.get_all_permissions %}
	<a id="delSoutenance" href="#" class="btn btn-danger">Supprimer</a>
	{% endif %}
</div>
<h1>Soutenance au {{ soutenance.datePassage }}</h1>
<br/>
<table class="table table-striped col-xs-12 col-lg-12">

	<tr><td><b>Stage :</b></td><td>{{ soutenance.stage.intitule }}</td></tr>
	<tr><td><b>Etudiant :</b></td><td>{{ soutenance.stage.etudiant.prenom }}
		{{ soutenance.stage.etudiant.nom }}</td></tr>
	<tr><td><b>Entreprise :</b></td><td>{{ soutenance.stage.entreprise.nom }}</td></tr>
	<tr><td><b>Maitre de stage :</b></td><td>{{ soutenance.stage.maitreStage.prenom }}
		{{ soutenance.stage.maitreStage.nom }}</td></tr>
	<tr><td><b>Enseignant tuteur:</b></td><td>{{ soutenance.stage.enseignantTuteur.prenom }}
		{{ soutenance.stage.enseignantTuteur.nom }}</td></tr>
	<tr><td><b>Date de passage :</b></td><td>{{ soutenance.datePassage }}</td></tr>
	<tr><td><b>Date de fin prévu :</b></td><td>{{ soutenance.dateFinPrevu }}</td></tr>
	<tr><td><b>Salle :</b></td><td>{{ soutenance.salle.num }}</td></tr>

</table>
{% endblock %}
{% block js %}
	{% if "planning.delete_soutenance" in user.get_all_permissions %}
	$('#delSoutenance').click(function(e){
		if (confirm("Êtes-vous sûr de vouloir supprimer cette soutenance ?")){
			$.ajax({
				url: '{% url 'delSoutenance' %}',
				data: {},
				type: 'GET'
	        }).done(function(data, textStatus, jqXHR){
	        	var form = data.split('<form action="" method="post">')[1]
					.split('</form>')[0];
	            $('body').append('<form action="{% url 'delSoutenance' %}" method="post" id="delForm"></form>');
	            $('#delForm').append(form);
	            $('#delForm input[value={{ soutenance.idSoutenance }}]').prop('checked', true);
	            $('#delForm').submit();
	        }).fail(function(jqXHR, textStatus, errorThrown){
	            console.log("ajax failed");
	            alert(errorThrown);
	        });
		}
	})
	{% endif %}

	active_tab="#tab-planning"
{% endblock %}