gestionStage/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # racine et page par defaut, pages classiques
    url(r'^/?$',"gestionStage.views.show_main", name="accueil"),
    url(r'^login/$', "gestionStage.forms.login_page", name="login"),
    url(r'^logout/$', "gestionStage.forms.logout_action", name="logout"),
    url(r'^oups/$',"gestionStage.views.oups",name="oups"),
    url(r'^recherche/$',"gestionStage.views.search",name="search"),

    # app entreprise
    url(r'^entreprise/', include('entreprise.urls')),
    url(r'^visiter/$', "entreprise.views.show_visiter", name="visiter"),

    # app stage
    url(r'^stage/', include('stage.urls')),

    # app planning
    url(r'^planning/', include('planning.urls')),


    url(r'^monProfilEtudiant/?$',"stage.views.monProfilEtu", name="monProfil"),
    url(r'^etudiant/(?P<pk>\d+)$',"stage.views.detailsEtudiant", name="detailsEtudiant"),
    url(r'^etudiant/modifier/(?P<pk>\d+)$',"stage.views.modifEtudiant", name="modifEtudiant"),

    url(r'^monProfilEnseignant/?$',"stage.views.monProfilEns", name="monProfil"),
    url(r'^enseignant/(?P<pk>\d+)$',"stage.views.detailsEnseignant", name="detailsEnseignant"),
    url(r'^enseignant/modifier/(?P<pk>\d+)$',"stage.views.modifEnseignant", name="modifEnseignant"),

    url(r'^findData/?$', "gestionStage.views.find_data", name="find_data")


)

stage/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'gestionStage.views.home', name='home'),
    # url(r'^gestionStage/', include('gestionStage.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
   
    url(r'^/?$',"stage.views.show_stages"),
    url(r'^(?P<pk>\d+)$',"stage.views.show_detail_stage", name="stage"),
    url(r'^modifier/(?P<pk>\d+)$',"stage.views.modifStage", name="modifStage"),
    url(r'^monStage/?$',"stage.views.monStage", name="theStage"),
    url(r'^ajouter/?$',"stage.views.addStage", name="addStage"),
    url(r'^supprimer/?$',"stage.views.delStage", name="delStage"),
    url(r'^logiciel/$',"stage.views.addLogiciel",name="addLogiciel"),
    url(r'^personne-ext/$',"stage.views.addPersonneExt",name="addPersonneExt"),
    url(r'^ok/?$',"stage.views.stage_operationEffectuee", name="stageOperationEffectuee"),
    url(r'^valider/?$',"stage.views.validerStage", name="validerStage"),
    url(r'^detailsvalider/(?P<pk>\d+)$',"stage.views.detailsValiderStage", name="detailsValiderStage"),
    url(r'^validerenbase/(?P<pk>\d+)$',"stage.views.validerStageEnBase", name="validerStageEnBase"),

    url(r'^offrestage/?$',"stage.views.showOffres", name="showOffres"),
    url(r'^offrestage/(?P<pk>\d+)$',"stage.views.detailsOffreStage", name="detailsOffreStage"),
    url(r'^offrestage/modifier/(?P<pk>\d+)$',"stage.views.modifOffreStage", name="modifOffreStage"),
    url(r'^offrestage/ajouter/?$',"stage.views.addOffreStage", name="addOffreStage"),
    url(r'^offrestage/supprimer/?$',"stage.views.delOffreStage", name="delOffreStage"),
    url(r'^offrestage/ok/?$',"stage.views.offreStage_operationEffectuee", name="offreStageOperationEffectuee"),
    url(r'^offrestage/valider/?$',"stage.views.validerOffreStage", name="validerOffreStage"),
    url(r'^offrestage/detailsvalider/(?P<pk>\d+)$',"stage.views.detailsValiderOffreStage", name="detailsValiderOffreStage"),
    url(r'^offrestage/validerenbase/(?P<pk>\d+)$',"stage.views.validerOffreStageEnBase", name="validerOffreStageEnBase"),
    #url(r'^offrestage/postuler/(?P<pk>\d+)$',"stage.views.postuler", name="postuler"),
    url(r'^offrestage/prendreOffre/(?P<pk>\d+)$',"stage.views.prendreOffre", name="prendreOffre"),
)

stage/models.py
# -*- coding: utf-8 -*-
from django import forms
from django.db import models
from django.contrib.auth.models import User
from entreprise.models import Entreprise
# Create your models here..


class Diplome(models.Model):
    idDiplome = models.AutoField(primary_key=True)
    nom = models.CharField(max_length=20)
    specialite = models.CharField(max_length=80)

    class Meta:
        ordering = ('nom',)

    def __str__(self):
        return self.nom



class Promotion(models.Model):
    idPromotion = models.AutoField(primary_key=True)
    intitule = models.CharField(max_length=20)
    annee = models.CharField(max_length=10)
    diplome = models.ForeignKey(Diplome)

    class Meta:
        ordering = ('intitule',)

    def __str__(self):
        return self.intitule+"-"+self.annee

    def natural_key(self):
        return {
            'intitule' : self.intitule
        }


class Personne(models.Model):
    nom=models.CharField(max_length=30)
    prenom=models.CharField(max_length=30)
    emailPerso = models.EmailField(max_length=80)
    typeCivilite = (('M.', 'Monsieur'),('Mme', 'Madame'),('Mlle', 'Mademoiselle'))
    civilite = models.CharField(max_length=15,choices=typeCivilite,default='M.')
    telephone = models.CharField(max_length=14, null=True, blank=True)
    
    class Meta:
        ordering = ('nom',)

    def __str__(self):
        return self.prenom +" "+ self.nom



class PersonneInterne(Personne):
    username=models.ForeignKey(User, related_name="personneInterne_username")

    def natural_key(self):
        return {
            'nom' : self.nom,
            'prenom' : self.prenom,
            'telephone' : self.telephone}



class Enseignant(PersonneInterne):
    idEnseignant = models.AutoField(primary_key=True)
    emailEns = models.EmailField(max_length=80)
    departement = models.CharField(max_length=80) # peut-être à séparer dans une classe département ?
    #numEns = models.IntegerField(primary_key=True)
    #grade = models.CharField(max_length=50)

    class Meta:
        permissions = (
            ("rechercherconsulter_enseignant", "Peut rechercher et consulter les fiches d'enseignants"),
        )

    def search_result_header():
        html="<thead><tr><th>Nom</th><th>Prénom</th><th>E-mail</th><th>Département</th></tr></thead>"
        return "%s" % (html)

    def search_result(self):
        html="<tr class=\"trLien\" onclick=\"document.location='/enseignant/"+str(self.idEnseignant)+"'\"><td>"+self.nom+"</td><td>"+self.prenom+"</td><td>"+self.emailEns+"</td><td>"+self.departement+"</td></tr>"
        return "%s" % (html)



class PersonneExterieure(Personne):
    idPersonneExt = models.AutoField(primary_key=True)
    emailPro = models.EmailField(max_length=80)
    entreprise=models.ForeignKey(Entreprise, related_name="personneExterieure_entreprise")

    def natural_key(self):
        return {
            'nom' : self.nom,
            'prenom' : self.prenom,
            'telephone' : self.telephone,
            'emailPro' : self.emailPro
        }



class Logiciel(models.Model):
    nomLog = models.CharField(primary_key=True, max_length=50)
    theme = models.CharField(max_length=50)
    description = models.CharField(max_length=400)

    class Meta:
        ordering = ('nomLog',)

    def __str__(self):
        return self.nomLog



class OffreStage(models.Model):
    intitule = models.CharField(max_length=100)
    sujet = models.CharField(max_length=512)
    # on stocke l'entreprise ici au cas où le tuteur de stage (personne ext) change d'entreprise
    entreprise = models.ForeignKey(Entreprise, related_name="stage_entreprise")
    nomLogiciels = models.ManyToManyField(Logiciel, null=True, blank=True)
    possibiliteEmbauche = models.NullBooleanField(null=True, default=None)
    valideOffreStage = models.NullBooleanField(default=False)
        #False : pas validé
        #True : validé
        #None : offre de stage prise par un étudiant

    class Meta:
        permissions = (
            ("valider_offrestage", "Peut valider une offre de stage"),
            ("postuler_offrestage", "Peut postuler à une offre de stage"),
            ("recuperer_offrestage", "Permet à un étudiant de créer son stage à partir d'une offre de stage"),
        )

    def natural_key(self):
        return {
            'intitule' : self.intitule,
            'entreprise' : self.entreprise.natural_key(),
            }

    def __str__(self):
        return self.intitule

    def search_result_header():
        html="<thead><tr><th>Intitulé</th><th>Entreprise</th></tr></thead>"
        return "%s" % (html)

    def search_result(self):
        idEnt = Entreprise.objects.get(nom=str(self.entreprise)).idEntreprise
        html='<tr><td><a href="/stage/offrestage/'+str(self.pk)+'">'+str(self.intitule)+'</a></td><td><a href="/entreprise/'+str(idEnt)+'">'+str(self.entreprise)+'</a></td></tr>'
        return "%s" % (html)

    def valider(self):
        setattr(self, 'valideOffreStage', True)
        self.save()
        return True

    def reserver(self):
        setattr(self, 'valideOffreStage', None)
        self.save()
        return True


class Etudiant(PersonneInterne):
    numEtu = models.IntegerField(primary_key=True)
    dateNaissance = models.DateField(verbose_name="Date de naissance")
    emailEtu = models.EmailField(max_length=80)
    adresse = models.CharField(max_length=100)
    cp = models.IntegerField(max_length=5)
    ville = models.CharField(max_length=50)
    promotion = models.ForeignKey(Promotion)
    postulant = models.ManyToManyField(OffreStage)

    class Meta:
        permissions = (
            ("rechercherconsulter_etudiant", "Peut rechercher et consulter les fiches d'étudiants"),
        )

    def search_result_header():
        html="<thead><tr><th>Promotion</th><th>Numéro</th><th>Nom</th><th>Prénom</th><th>E-mail</th></tr></thead>"
        return "%s" % (html)

    def search_result(self):
        html="<tr class=\"trLien\" onclick=\"document.location='/etudiant/"+str(self.numEtu)+"'\"><td>"+str(self.promotion)+"</td><td>"+str(self.numEtu)+"</td><td>"+self.nom+"</td><td>"+self.prenom+"</td><td>"+self.emailEtu+"</td></tr>"
        return "%s" % (html)

    def natural_key(self):
        return {'numEtu' : self.numEtu,
            'nom' : self.nom,
            'prenom' : self.prenom,
            'telephone' : self.telephone
            }


class Stage(OffreStage):
    idStage = models.AutoField(primary_key=True)
    etudiant = models.ForeignKey(Etudiant, related_name="stage_etudiant")
    dateDebut = models.DateField()
    dateFin = models.DateField()
    persConvention = models.ForeignKey(PersonneExterieure, related_name="stage_persConvention")
    maitreStage = models.ForeignKey(PersonneExterieure, related_name="stage_maitreStage")
    enseignantTuteur = models.ForeignKey(Enseignant, related_name="stage_enseignantTuteur")
    valideStage = models.BooleanField(default=False) 
    # Un étudiant peut changer de promotion donc on préfère stocker la promotion dans le stage
    # promotion = models.ForeignKey(Promotion)


    class Meta:
        ordering = ('intitule',)
        permissions = (
            ("valider_stage", "Peut valider un stage"),
            ("genererdocuments_stage", "Peut générer les documents propres à un stage (convention)"),
            ("noter_stage", "Peut noter un stage"),
        )

    def __str__(self):
        return self.intitule

    def natural_key(self):
        return {
            'id' : self.idStage,
            'intitule' : self.intitule,
            'sujet' : self.sujet,
            'dateDeDebut' : self.dateDebut,
            'dateDeFin' : self.dateFin,
            'etudiant' : self.etudiant.natural_key(),
            'maitreStage' : self.maitreStage.natural_key(),
            'enseignantTuteur' : self.enseignantTuteur.natural_key()
        }

    def search_result_header():
        html="<thead><tr><th>Intitulé</th><th>Etudiant</th><th>Enseignant Tuteur</th><th>Entreprise</th></tr></thead>"
        return "%s" % (html)

    def search_result(self):
        idEnt = Entreprise.objects.get(nom=str(self.entreprise)).idEntreprise
        idEns = Enseignant.objects.get(nom=str(self.enseignantTuteur.nom)).idEnseignant
        idEtu = Etudiant.objects.get(nom=str(self.etudiant.nom)).numEtu
        html='<tr><td><a href="/stage/'+str(self.idStage)+'">'+self.intitule+'</td><td><a href="/etudiant/'+str(idEtu)+'">'+str(self.etudiant)+'</a></td><td><a href="/enseignant/'+str(idEns)+'">'+str(self.enseignantTuteur)+'</a></td><td><a href="/entreprise/'+str(idEnt)+'">'+str(self.entreprise)+'</a></td></tr>'
        return "%s" % (html)

    def valider(self):
        setattr(self, 'valideStage', True)
        self.save()
        return True


class EnseignantResp(models.Model):
    enseignant = models.ForeignKey(Stage,related_name="EnseignantResp_enseignant")
    stage = models.ManyToManyField(Stage)
    priorite_reservation = models.IntegerField(max_length=2)
    validation_resp=models.BooleanField(default=False)

stage/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from django import forms
from django.forms.extras.widgets import SelectDateWidget
from stage.models import *
from django.shortcuts import render
from django.contrib.auth.models import User


class StageFormEtu(ModelForm):
    etudiant = forms.ModelChoiceField(queryset=Etudiant.objects.all(),
            widget=forms.HiddenInput())
    dateDebut = forms.DateField(widget=SelectDateWidget())
    dateFin = forms.DateField(widget=SelectDateWidget())

    class Meta:
        model = Stage
        exclude = ['valideOffreStage', 'valideStage']


class StageForm(ModelForm):
    dateDebut = forms.DateField(widget=SelectDateWidget())
    dateFin = forms.DateField(widget=SelectDateWidget())

    class Meta:
        model = Stage
        exclude = ['valideOffreStage', 'valideStage']


class supprimeStageForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(supprimeStageForm, self).__init__(*args, **kwargs)
        self.fields['stageslots'].label = "Selectionnez les stages à supprimer"
    # You can change the queryset in the __init__ method, but this should be a nice basis
        
    stageslots = forms.ModelMultipleChoiceField(queryset=Stage.objects.all(), widget=forms.CheckboxSelectMultiple(),required=False)

    def save(self):
        # make sure you do a form.is_valid() before trying to save()
        for stageslot in self.cleaned_data['stageslots']:
            stageslot.delete()
    def list(self):
        # make sure you do a form.is_valid() before trying to save()
        for stageslot in self.cleaned_data['stageslots']:
            print(stageslot)
    class Meta:
        model = Stage
        fields ='stageslots'


class PersonneExtForm(ModelForm):
    class Meta:
        model = PersonneExterieure

class LogicielForm(ModelForm):
    class Meta:
        model = Logiciel   
        

class OffreStageForm(ModelForm):
    class Meta:
        model = OffreStage
        exclude = ['valideOffreStage']

class supprimeOffreStageForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(supprimeOffreStageForm, self).__init__(*args, **kwargs)
        self.fields['offrestagelots'].label = "Selectionnez les offres de stage à supprimer"
    # You can change the queryset in the __init__ method, but this should be a nice basis
        
    offrestagelots = forms.ModelMultipleChoiceField(queryset=OffreStage.objects.filter(valideOffreStage=True) | OffreStage.objects.filter(valideOffreStage=False), widget=forms.CheckboxSelectMultiple(),required=False)

    def save(self):
        # make sure you do a form.is_valid() before trying to save()
        for offrestagelots in self.cleaned_data['offrestagelots']:
            offrestagelots.delete()
    def list(self):
        # make sure you do a form.is_valid() before trying to save()
        for offrestagelots in self.cleaned_data['offrestagelots']:
            print(offrestagelots)
    class Meta:
        model = Stage
        fields ='offrestagelots'



class EtudiantForm(ModelForm):
    class Meta:
        model = Etudiant
        exclude = ['postulant']


class EnseignantForm(ModelForm):
    class Meta:
        model = Enseignant

stage/templates/offrestage/details_offrestage.html
{% extends "base.html" %}
{% block title %}{{ block.super }} | Détails de l'offre de stage {% endblock %}
{% block main %}

<span class="details_etu">
<h1 class="page-heading">{{ offrestage.intitule }}
	<small>{{ offrestage.entreprise }}</small>
	{% if perms.stage.change_offrestage %}
		<a class="pull-right btn btn-primary" href="{% url 'modifOffreStage' pk=offrestage.pk %}">Modifier</a>
	{% endif %}
	{% if perms.stage.postuler_offrestage %}
		<a class="pull-right btn btn-primary" href="#">Postuler</a>
	{% endif %}
</h1> 
</span><br/>

<table class="table table-striped col-xs-12 col-lg-12">

	<tr><td><b>Intitulé :</b></td><td> {{ offrestage.intitule }}</td></tr> 
	<tr><td><b>Sujet :</b></td><td> {{ offrestage.sujet }}</td></tr>
	<tr><td><b>Logiciel :</b></td>
		<td><ul>
		{% for log in offrestage.nomLogiciels.all %}
			<li>{{ log }}</li>
		{% endfor %}
		</ul></td>
	</tr>
	<tr><td><b>Entreprise :</b></td><td> {{ offrestage.entreprise.nom }}</td></tr> 
	<tr><td><b>Adresse :</b></td><td> {{ offrestage.entreprise.adresse }}</td></tr> 
	<tr><td><b>Code postal :</b></td><td> {{ offrestage.entreprise.codePostal }}</td></tr> 
	<tr><td><b>Ville :</b></td><td> {{ offrestage.entreprise.ville }}</td></tr> 
	<tr><td><b>Tel :</b></td><td> {{ offrestage.entreprise.telephone }}</td></tr> 
	<tr><td><b>Fax :</b></td><td> {{ offrestage.entreprise.fax }}</td></tr> 
	

</table>

{% endblock %}
{% block js %}active_tab="#tab-stage"{% endblock %}

stage/templates/offrestage/details_valider_offrestage.html
<span class="details_etu">
	<h1 class="page-heading">{{ offrestage.intitule }}
		<small>{{ offrestage.entreprise }}</small>
	</h1> 
</span>

<br/>

<table class="table table-striped col-xs-12 col-lg-12">

	<tr><td><b>Intitulé :</b></td><td> {{ offrestage.intitule }}</td></tr> 
	<tr><td><b>Sujet :</b></td><td> {{ offrestage.sujet }}</td></tr>
	<tr><td><b>Logiciel :</b></td>
		<td><ul>
		{% for log in offrestage.nomLogiciels.all %}
			<li>{{ log }}</li>
		{% endfor %}
		</ul></td>
	</tr>
	<tr><td><b>Entreprise :</b></td><td> {{ offrestage.entreprise.nom }}</td></tr> 
	<tr><td><b>Adresse :</b></td><td> {{ offrestage.entreprise.adresse }}</td></tr> 
	<tr><td><b>Code postal :</b></td><td> {{ offrestage.entreprise.codePostal }}</td></tr> 
	<tr><td><b>Ville :</b></td><td> {{ offrestage.entreprise.ville }}</td></tr> 
	<tr><td><b>Tel :</b></td><td> {{ offrestage.entreprise.telephone }}</td></tr> 
	<tr><td><b>Fax :</b></td><td> {{ offrestage.entreprise.fax }}</td></tr> 
	
</table>

stage/templates/offrestage/forms.html
{% extends "base.html" %}
{% block title %}{{ block.super }} | {{ actionAFaire }} {% endblock %}
{% block main %}
	<form action="" method="post">{% csrf_token %}
	<table>
		{{ form.as_table }}
		</table>
		<input class="btn btn-success" type="submit" value="{{ actionAFaire }}" />
	</form>
{% endblock %}

{% block js %}active_tab="#tab-stage"{% endblock %}

stage/templates/offrestage/offrestage.html
{% extends "base.html" %}
{% block title %}{{ block.super }} | Offres de stages {% endblock %}
{% block main %}
<h1>Offres de stage</h1>
<br/>
	<div class="menu col-xs-12 col-sm-2 col-lg-2">
	{% if "stage.add_offrestage" in user.get_all_permissions %}
		<a class="btn btn-primary" href="{% url 'addOffreStage' %}">Ajouter</a><br/>
	{% endif %}
	{% if "stage.delete_offrestage" in user.get_all_permissions %}
		<a class="btn btn-danger" href="{% url 'delOffreStage' %}">Supprimer</a>
	{% endif %}
	</div>
	<ul class="col-xs-12 col-sm-offset-1 col-lg-8">
		{% for o in liste_offrestage %}
			{% if o.valideOffreStage == True %}
				<li><a href="{% url 'detailsOffreStage' pk=o.pk %}">{{ o }}</a></li><br/>
			{% endif %}
		{% endfor %}
	</ul>

{% endblock %}
{% block js %}active_tab="#tab-stage"{% endblock %}

stage/templates/offrestage/operation_effectuee.html
{% extends "base.html" %}
{% block title %}{{ block.super }} | Offres de stages {% endblock %}
{% block main %}

<div class="alert alert-success">
<h4><strong>Opération effectuée</strong></h4>
<p>Votre offre de stage a bien été enregistrée, elle est maintenant en attente de validation par un responsable.</p>
</div>
<a href="/">Retour à l'accueil</a>

{% endblock %}
{% block js %}active_tab="#tab-stage"{% endblock %}

stage/templates/offrestage/valideroffrestage.html
{% extends "base.html" %}
{% block title %}{{ block.super }} | Offres de stages {% endblock %}
{% block main %}
	<h1>Offres de stage non validées</h1>
	<br/>

	<div class="menu col-xs-12 col-sm-2 col-lg-2">
	{% if "stage.add_offrestage" in user.get_all_permissions %}
		<a class="btn btn-primary" href="{% url 'addOffreStage' %}">Ajouter</a><br/>
	{% endif %}
	{% if "stage.delete_offrestage" in user.get_all_permissions %}
		<a class="btn btn-danger" href="{% url 'delOffreStage' %}">Supprimer</a>
	{% endif %}
	</div>

	<ul id="offres_stage" class="col-xs-12 col-sm-offset-1 col-lg-8">
		{% for o in liste_offrestage %}
			{% if o.valideOffreStage == False %}
				<!-- <li><a href="{% url 'detailsOffreStage' pk=o.pk %}">{{ o }}</a></li><br/>-->
				<li><a href="#" onclick="javascript:openDialog()" value="{{o.pk}}">{{ o }}</a></li><br/>
			{% endif %}
		{% endfor %}
	</ul>

	<div id="dialog" >
		<div id="content"></div>
	</div>
	


{% endblock %}

{% block libraries %}{{ block.super }}
	<link rel="stylesheet" type="text/css" href="/static/css/smoothness/jquery-ui-1.10.4.custom.min.css" media="screen">
	<script type="text/javascript" src="/static/js/jquery-ui-1.10.4.custom.min.js"></script>
	<script type="text/javascript" src="/static/js/utils.js"></script>
{% endblock %}

{% block js %}

	$(document).ready( function(){
		active_tab="#tab-stage"

		$("#offres_stage a").click(function(){
			var idoffre = $(this).attr("value");
			$.ajax({
				url: "./detailsvalider/"+idoffre,
				data: {},
				type: 'GET',
				dataType: 'html'
			}).done(function(data, textStatus, jqXHR){
				var html = data;
				$("#dialog #content").html(html);
		
				function validerOffreStage() {
					if (confirm("Êtes-vous sûr de vouloir valider cette offre ?")) {
						$.ajax({
							url: "./validerenbase/"+idoffre,
							data: {},
							type: 'GET',
							dataType: 'html'
						}).done(function(data, textStatus, jqXHR){
							location.reload();
						}).fail(function(jqXHR, textStatus, errorThrown){
							console.log("ajax failed");
							alert(errorThrown);
						});
					}
				}

				$("body").append($('<button id="open_dialog" style="display:none;"></button>'));
				genDialogForm($("#dialog"), $("#open_dialog"), 700, 600, validerOffreStage);
				$("#open_dialog").click();
			}).fail(function(jqXHR, textStatus, errorThrown){
				console.log("ajax failed");
				alert(errorThrown);
			});
			$("#dialog").dialog('open');
		});

	});


	

{% endblock %}